#!/usr/bin/env python3

MONTHS = [
	'January', 
	'February', 
	'March', 
	'April', 
	'May', 
	'June', 
	'July', 
	'August', 
	'September',
	'October', 
	'November', 
	'December'
]

US_STATES_CODES = {
	'Alabama': 'AL',
	'Alaska': 'AK',
	'Arizona': 'AZ',
	'Arkansas': 'AR',
	'California': 'CA',
	'Colorado': 'CO',
	'Connecticut': 'CT',
	'Delaware': 'DE',
	'District of Columbia': 'DC',
	'Florida': 'FL',
	'Georgia': 'GA',
	'Hawaii': 'HI',
	'Idaho': 'ID',
	'Illinois': 'IL',
	'Indiana': 'IN',
	'Iowa': 'IA',
	'Kansas': 'KS',
	'Kentucky': 'KY',
	'Louisiana': 'LA',
	'Maine': 'ME',
	'Maryland': 'MD',
	'Massachusetts': 'MA',
	'Michigan': 'MI',
	'Minnesota': 'MN',
	'Mississippi': 'MS',
	'Missouri': 'MO',
	'Montana': 'MT',
	'Nebraska': 'NE',
	'Nevada': 'NV',
	'New Hampshire': 'NH',
	'New Jersey': 'NJ',
	'New Mexico': 'NM',
	'New York': 'NY',
	'North Carolina': 'NC',
	'North Dakota': 'ND',
	'Northern Mariana Islands': 'MP',
	'Ohio': 'OH',
	'Oklahoma': 'OK',
	'Oregon': 'OR',
	'Palau': 'PW',
	'Pennsylvania': 'PA',
	'Puerto Rico': 'PR',
	'Rhode Island': 'RI',
	'South Carolina': 'SC',
	'South Dakota': 'SD',
	'Tennessee': 'TN',
	'Texas': 'TX',
	'Utah': 'UT',
	'Vermont': 'VT',
	'U.S. Virgin Islands': 'VI',
	'Virginia': 'VA',
	'Washington': 'WA',
	'West Virginia': 'WV',
	'Wisconsin': 'WI',
	'Wyoming': 'WY',
	'Guam': 'GU',
	'American Samoa': 'AS',
	'Rota': 'MP',
	'Saipan': 'MP'
}

WEATHER_DATA = [
	'Average Temperature',
	'Average Precipitation',
	'Average Number of Days With Precipitation',
	'Average Relative Humidity',
	'Average Dew Point',
	'Cooling Degree Days',
	'Growing Degree Days',
	'Average Length of Day',
	'Average Possibility of Sunshine',
	'Average Wind Speed',
	'Average Daily Solar Radiation - Diffuse',
	'Average Daily Solar Radiation - Direct',
	'Average Daily Solar Radiation - Global',
	'Average Daily Solar Radiation - Reflected',
	'Maximum Daily Solar Radiation - Diffuse',
	'Maximum Daily Solar Radiation - Direct',
	'Maximum Daily Solar Radiation - Global',
	'Maximum Daily Solar Radiation - Reflected',
	'Minimum Daily Solar Radiation - Diffuse',
	'Minimum Daily Solar Radiation - Direct',
	'Minimum Daily Solar Radiation - Global',
	'Minimum Daily Solar Radiation - Reflected',
]

ALTERNATIVE_DATA = [
	'Average Temperature',
	'Average Low Temperature',
	'Average High Temperature',
	'Average Precipitation',
#	'Average Number of Days With Precipitation',
	'Average Relative Humidity',
#	'Average Dew Point',
	'Cooling Degree Days',
	'Growing Degree Days',
	'Average Length of Day',
#	'Average Possibility of Sunshine',
#	'Average Wind Speed',
#	'Average Daily Solar Radiation - Diffuse',
	'Average Daily Solar Radiation - Direct',
	'Average Daily Solar Radiation - Global',
#	'Average Daily Solar Radiation - Reflected',
]

def main():
	pass

if __name__ == '__main__':
	main()